"""feat: add kyc biometric fields to users

Revision ID: cd1e198e40b8
Revises: 1d36690de02c
Create Date: 2026-04-12 20:57:15.710758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1e198e40b8'
down_revision: Union[str, None] = '1d36690de02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_kyc_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('kyc_baseline_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_baseline_path')
    op.drop_column('users', 'is_kyc_verified')
    # ### end Alembic commands ###
